% Stratifiable two-people game
% Equivalent to the nonstratifiable:
% winning(X) :- move(X,Y), not(winning(X)).
% April, 2011

move(1,2).
move(2,3).
move(3,4).
move(1,3).
move(1,5).

canMove(X):-
  move(X,Y).

possible_winning(X):-
  odd_move(X,Y),
  not(canMove(Y)).

winning(X):-
  move(X,Y),
  not(possible_winning(Y)).

odd_move(X,Y) :-
  move(X,Y).
odd_move(X,Y) :-
  move(X,Z1),
  move(Z1,Z2),
  odd_move(Z2,Y).
